# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return

    obj = bld.create_ns3_program('single-bird-orbit', ['icarus'])
    obj.source = 'single-bird-orbit.cc'

    obj = bld.create_ns3_program('intermittent-communication', ['icarus'])
    obj.source = 'intermittent-communication.cc'

    obj = bld.create_ns3_program('sputping', ['icarus'])
    obj.source = 'sputping.cc'

    obj = bld.create_ns3_program('vostping', ['icarus'])
    obj.source = 'vostping.cc'

    obj = bld.create_ns3_program('constellation-positions', ['icarus'])
    obj.source = 'constellation-positions.cc'

    obj = bld.create_ns3_program('isl-vostping', ['icarus'])
    obj.source = 'isl-vostping.cc'

    obj = bld.create_ns3_program('isl-grid', ['icarus'])
    obj.source = 'isl-grid.cc'

    obj = bld.create_ns3_program('ground2groundping', ['icarus'])
    obj.source = 'ground2groundping.cc'
