# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        build: [debug, optimized]
        compiler: [g++-10, clang++-12]

    # The type of runner that the job will run on
    runs-on: self-hosted

    name: Build ${{ matrix.build }} with ${{ matrix.compiler }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout pybindgen
        uses: actions/checkout@v2
        with:
          repository: gjcarneiro/pybindgen
          path: pybindgen
          ref: '0.22.0'
      - name: Install dependencies
        run: sudo apt install -y build-essential libsqlite3-dev libboost-all-dev libssl-dev git python3-setuptools castxml
      - name: Checkout ns3 version of ndnSIM
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: named-data-ndnSIM/ns-3-dev
          path: ns-3
      - name: Checkout ndnSIM
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: named-data-ndnSIM/ndnSIM
          path: ns-3/src/ndnSIM
          submodules: recursive
      - name: Checkout ICARUS
        uses: actions/checkout@v2
        with:
          path: ns-3/src/icarus
      - name: Configure
        run: |
          cd ns-3
          CXX=${{ matrix.compiler }} ./waf configure -d ${{ matrix.build }} --enable-tests --enable-examples -o build/${{ matrix.build }}/${{ matrix.compiler }} --enable-modules=icarus,point-to-point-layout
      - name: Build
        run: |
          cd ns-3
          ./waf build
      - name: Check
        run: |
          cd ns-3
          ./test.py -m -s icarus -v
          ./test.py -m -s icarus.sataddress -v
